### ISSUE TITLE
Table Drop-down broken

### ISSUE THREAD

**Issue by ntautges** [ucd-library/pgdm-ui#4]
When I typed in "harvest" to select which table to insert spreadsheet into, it correctly pulled up the harvest_ sheets, but when I clicked on harvest_measurement_view, it did not select that table.

**Comment by jrmerz** [comment]
fixed here 3bf4571

**Comment by jrmerz** [comment]
Update app via git cli to see changes

**Comment by ntautges** [comment]
Got it, thanks!

Sent from my iPhone

On Jul 16, 2019, at 10:31 AM, Justin Merz <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #4<https://github.com/ucd-library/pgdm-ui/issues/4>.
